# These are supported funding model platforms

github: BuxOrg
custom: https://getbux.io/?utm_source=github&utm_medium=sponsor-link&utm_campaign=bux-kube-controller&utm_term=bux-kube-controller&utm_content=bux-kube-controller
