# permissions for end users to edit buxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bux-editor-role
rules:
- apiGroups:
  - server.getbux.io
  resources:
  - buxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.getbux.io
  resources:
  - buxes/status
  verbs:
  - get
