---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - server.buxorg.io
  resources:
  - buxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.buxorg.io
  resources:
  - buxes/finalizers
  verbs:
  - update
- apiGroups:
  - server.buxorg.io
  resources:
  - buxes/status
  verbs:
  - get
  - patch
  - update
