blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/BuxOrg/bux-kube-controller/discussions
    about: Ask questions and discuss with other community members
