apiVersion: server.getbux.io/v1alpha1
kind: Bux
metadata:
  name: bux-sample
spec:
  configuration:
    adminXpub: "<admin_xpub>"
    autoMigrate: true
    enablePaymail: true
    requireSigning: true
  domain: "<domain>"
  clusterIssuer: "<cluster_issuer>"
  console: true
